const cars = [
  {
    id: 93278,
    name: "Bugatti Veyron Grand Sport Roadster",
    mileage: 2720,
    year: 2013,
    price: "",
    image: "https://gvelondon.com/wp-content/uploads/2022/09/9-4.jpg",
    overview:
      "Here is an opportunity to own one of the greatest achievements in all of automotive history. Introducing our Bugatti Veyron Grand Sport Roadster! Limited to 150 units worldwide, this is one of the fastest production Roadster's in history with a top speed of 407km/h with the roof up and 360km/h with the roof down. Like the 16.4, the Grand Sport produces 1001HP and sprints from zero to 60 mph in just 2.7 seconds. This car demonstrates that it is possible to create a roadster version of a hypercar whilst maintaining the incredible speed and dynamics without compromising on comfort and safety. By removing the roof, the passengers are directly exposed to the 8.0 litre quad turbo W16 which increases the unique and emotional experience of the Veyron and the transparent roof allows drivers to directly experience their surroundings, even when the roof is up. The larger Roof Spoiler allows for a more comfortable and relaxed drive at such speeds by reducing noise in the cabin making for the perfect roof down drive. This stunning UK Supplied Bugatti Veyron Grand Sport Roadster has been finished in Pearl White and has been fitted with Polished Alloy Wheels with Diamond Cut Surfaces complete with black brake calipers. This example includes Carbon Fibre Front Spoiler as well as Black Leather Interior with Berry White Contrast Stitching. This vehicle is UK supplied and has been kept in pristine condition as shown by its full Bugatti Service History. Walk around video available upon request. Nationwide delivery available. All vehicles undergo a full visual and mechanical health check by GVE Servicing and preparation by GVE detailing. Get in touch with any customisation or servicing needs. Please call to confirm specifications as variations can occur. Excellent bodywork, Interior - Excellent Condition, Tyre condition Excellent, 12 Month warranty available - JBR/ Aldermore/ Black Horse Partner. Major credit/ debit cards accepted. Please view on our website.",
    specifications: [
      "Pearl White Exterior Paint",
      "Polished Alloy Wheels with Diamond Cut Surfaces",
      "Black Brake Calipers",
      "Carbon Fibre Front Splitter",
      "Air Intakes in Black",
      "Black Leather Interior",
      "Contrast Stitching in Berry White",
    ],
  },
  {
    id: 81015,
    name: "Rolls Royce Cullinan V12 Black Badge",
    mileage: 2000,
    year: 2022,
    price: 439900,
    image: "https://gvelondon.com/wp-content/uploads/2022/11/9-19.jpg",
    overview:
      "This VAT Qualifying Rolls Royce Cullinan Black Badge has a bewildering approach with hand-built attention to detail, material quality, refinement and comfort. The Cullinan gets its name from the largest diamond ever discovered, emphasising its pure and precious build. The Rolls Royce Cullinan has wonderfully plush, luxurious and modern interior, sleek black accents and a more powerful engine.This specific Rolls Royce Cullinan Black Badge comes with optional extras such as the Drivers Package, Black Badge Technical Carbon, Front Massage Seats, Rolls Royce Bespoke Audio, Coloured Stitching, Rear Theatre Configuration, Lounge Seats and Automatic Door Close.The heart of this Rolls Royce Cullinan Black Badge is a 6.75 litre V12 twin-turbocharged that pushes 591bhp through all four wheels and an 8-speed automatic gearbox. This ensures the Cullinan sprints to speeds of 155mph and a 0-60 time of only 5.1 Seconds.Walk around video available upon request. Nationwide delivery available. All vehicles undergo a full visual and mechanical health check by GVE Servicing and preparation by GVE detailing. Get in touch with any customisation or servicing needs. Please call to confirm specifications as variations can occur. Excellent bodywork, Interior - Excellent Condition, Tyre condition Excellent, 12 Month warranty available - JBR/Aldermore/Black Horse Partner. Major credit/debit cards accepted.",
    specifications: [
      "Black Diamond - Main Paint",
      "22 Part Polished Black Badge Wheels",
      "Red Brake Callipers",
      "Dark Chrome Spirit Of Ecstasy",
      "Black Badge Technical Carbon",
      "Lounge Seat",
      "Rear Privacy Glass",
      "Universal Garage Door Opener",
      "Rear Theatre Configuration",
      "Picnic Tables",
      "Lambs Wool Foot Mats",
      "Automatic Door Close",
      "Illuminated Black Badge Tread Plates",
      "Refrigerant",
      "Head Up Display",
      "Drivers Package",
      "Front Massage Seats",
      "Rolls-Royce Bespoke Audio",
      "Bespoke Interior",
      "Active Cruise Control",
      "Park Assistant",
      "Extended Veneer Centre Line",
      "SoE Embossed On Doors",
      "Rear Comfort Headrest Cushions",
      "Contrast Seat Piping",
      "Coloured Stitching",
      "Instrumental Panel With Top Stitch",
      "Extended Leather Headliner",
      "Stolen Vehicle Tracking",
      "Night Vision With Pedestrian Recognition",
    ],
  },
  {
    id: 28156,
    name: "Lamborghini Aventador SV LP750-4",
    mileage: 15214,
    year: 2015,
    price: 269900,
    image: "https://gvelondon.com/wp-content/uploads/2022/08/8-25.jpg",
    overview:
      "This stunning Lamborghini Aventador SV has been finished in Giallo and has been fitted with 20 Diamond Forged Rims complete with Giallo Brake Calipers. This pristine example includes many factory options such as Sports Exhaust, SV Logo, Suspension Lifting System, Rear View Camera as well as Navigation and Infotainment System. The Engine powering this Aventador SV is a 6.5L V12 which produces 740bhp along with a top speed of 217mph, allowing for a 0-60mph time of just 2.8 Seconds. Walk around video available upon request. Nationwide delivery available. All vehicles undergo a full visual and mechanical health check by GVE Servicing and preparation by GVE detailing. Get in touch with any customisation or servicing needs. Please call to confirm specifications as variations can occur. Excellent bodywork, Interior - Excellent Condition, Tyre condition Excellent, 12 Month warranty available - JBR/Aldermore/Black Horse Partner. Major credit/debit cards accepted.",
    specifications: [
      "Branding Package With Alcantara",
      "Sports Exhaust Upgrade",
      "SV Logo",
      "Suspension Lifting System",
      "Rear View Camera",
      "Diamond Forged Rims",
      "Giallo Painted Brake Calipers",
      "Giallo Orion Special Colours",
      "Navigation & Infotainment System",
    ],
  },
  {
    id: 65022,
    name: "Ferrari 821 Superfast",
    mileage: 1653,
    year: 2018,
    price: 249900,
    image: "https://gvelondon.com/wp-content/uploads/2022/12/9-2-4.jpg",
    overview:
      "The soul-achingly beautiful Ferrari 812 Superfast, known for its superiority and distinctiveness, is as fast and responsive as you dream a Ferrari should be and offers a smooth, sporty Ferrari experience. The 812's cabin provides seating for two, with reasonably spacious accommodations, good ergonomics, and modern design. From the soothing suspension to the phenomenal traction, to its blissful roar and aesthetically pleasing appearance the 812 never ceases to impress. This specific Ferrari 812 comes incredibly loaded with a Carbon Fibre Steering Wheel + LED's, Passenger Display, 20 Forged Painted Rims, Suspension Lifter, Front And Rear Parking Cameras, Adaptive Headlights With SBL Function and a NavTrak Anti Theft System Sub. This Naturally Aspirated V-12 powers 789bhp, reaching a top speed of 211mph and a 0-60 time of only 2.9 Seconds, not to mention its seven-speed dual-clutch transmission, standard carbon-ceramic brakes and additional Aero-cluster on the front to increase downforcnd balance aero load. Not to mention that in 2018, according to Ferrari, this engine was the most powerful naturally aspirated production car engine ever made. Walk around video available upon request. Nationwide delivery available. All vehicles undergo a full visual and mechanical health check by GVE Servicing and preparation by GVE detailing. Get in touch with any customisation or servicing needs. Please call to confirm specifications as variations can occur. Excellent bodywork, Interior - Excellent Condition, Tyre condition Excellent, 12 Month warranty available - JBR/ Aldermore/ Black Horse Partner. Major credit/ debit cards accepted.",
    specifications: [
      "Interior In Cream",
      "Cavallino Stitched On Headrest",
      "High Emotion Low Emission",
      "Carbon Fibre Steering Wheel + LED's",
      "Passenger Display",
      "Full Electric Seats",
      "Exterior Paint In Rosso Corsa",
      "Red Brake Callipers",
      "20' Forged Painted Rims",
      "Front & Rear Parking Cameras",
      "NavTrak Anti Theft System Sub",
      "Adaptive Headlights With SBL Function",
    ],
  },
  {
    id: 94722,
    name: "Mercedes SLR Mclaren",
    mileage: 30624,
    year: 2005,
    price: 239900,
    image: "https://gvelondon.com/wp-content/uploads/2022/04/9-50.jpg",
    overview:
      "This stunning Mercedes McLaren SLR has been finished in Crystal Laurit Silver and has been fitted with 19 Turbine Wheels complete with Red Brake Calipers. This pristine example includes Garage Door Opener, Electronically Adjustable Wing, Berry Red Exclusive Leather Interior, Electronically Adjustable Seats, Interior Motion Sensor and Carbon Fibre Seats. The Engine powering this SLR is a 5.4L Supercharged V8 which produces 617bhp along with a top speed of 207mph, allowing for a 0-60mph time of 3.6 Seconds. Walk around video available upon request. Nationwide delivery available. All vehicles undergo a full visual and mechanical health check by GVE Servicing and preparation by GVE detailing. Get in touch with any customisation or servicing needs. Please call to confirm specifications as variations can occur. Excellent bodywork, Interior - Excellent Condition, Tyre condition Excellent, 12 Month warranty available - JBR/Aldermore/Black Horse Partner. Major credit/debit cards accepted. THIS VEHICLE IS IMPORTED.",
    specifications: [
      "Crystal Laurit Silver Metallic Exterior Paint",
      "19 Turbine Wheels",
      "Red Brake Calipers",
      "Garage Door Opener",
      "Berry Red Exclusive Leather Interior",
      "Electronically Adjustable Seats",
      "Carbon Fibre Seats",
      "Interior Motion Sensor",
      "Bluetooth",
    ],
  },
  {
    id: 22156,
    name: "Porsche 911 GT2RS",
    mileage: 3010,
    year: 2018,
    price: 379900,
    image: "https://gvelondon.com/wp-content/uploads/2022/12/9.jpg",
    overview:
      "The Porsche GT2 RS compromises its name with pure performance, agility and speed. It builds grip no matter the speed, along with the downforce, razor-sharp turning and ceramic composite brakes and holds its balance. Including 2 different driving modes, this car can be used for everyday driving or track day at any time. This specific Porsche GT2 RS holds extras such as the Weissach Package, Sport Chrono Package, Magnesium Wheels, and LED Main Headlights In Black Including Porsche Dynamic Light System. The heart of this extremely capable beast is a 3.8-litre six-cylinder aluminium twin-turbo horizontally opposed engine that's pushing out 700bhp, reaching immaculate top speeds of 211mph and a 0-60 time of a rapid 2.7 Seconds. Power is sent through a rigidly mounted performance based seven-speed PDK gearbox to the rear wheels. Walk around video available upon request. Nationwide delivery available. All vehicles undergo a full visual and mechanical health check by GVE Servicing and preparation by GVE detailing. Get in touch with any customisation or servicing needs. Please call to confirm specifications as variations can occur. Excellent bodywork, Interior - Excellent Condition, Tyre condition Excellent, 12 Month warranty available - JBR/Aldermore/Black Horse Partner. Major credit/debit cards accepted.",
    specifications: [
      "Weissach Package",
      "Magnesium Wheels",
      "Preparation Outer Door-Sill Guards, Illuminated",
      "Sport Chrono Package",
      "Wheels Painted In Satin Black (Complete)",
      "Steering Wheel Rim And Gear Selection In Smooth-Finish Leather Black",
      "Passenger Footwell Storage Net",
      "Door Sill Guards In Carbon, Illuminated",
    ],
  },

  {
    id: 02322,
    name: "Aston Martin Zagato Coupe",
    mileage: 812,
    year: 2018,
    price: 449900,
    image: "https://gvelondon.com/wp-content/uploads/2022/10/9-7.jpg",
    overview:
      "This stunning VAT Qualifying Aston Martin Vanquish Zagato Coupe , finished in Cherry Tree Exterior Paint, has been fitted with 15 Spoke Satin Black Dt Bronze Tinted Wheels complete with Dark Anodised Brake Calipers. This pristine example has been fitted with Black Damson Leather Interior, Cream Truffle Stitching, Graduated Z Quilt Stitching, Obsidian Black Carpet Colour, Black Side Window Finisher and 2 + 2 Seating Arrangement. This highly specified example comes equipped with Alarm Upgrade Volumetric & Tilt Sensors, Black Textured Tailpipe Finisher, Sports Seat - Isofix and Q By Aston Martin. The Engine powering this Zagato Coupe is a 5.9L V12, producing 592bhp with a top speed of 200mph, reaching 0-60mph in 3.5 Seconds.Walk around video available upon request. Nationwide delivery available. All vehicles undergo a full visual and mechanical health check by GVE Servicing and preparation by GVE detailing. Get in touch with any customisation or servicing needs. Please call to confirm specifications as variations can occur. Excellent bodywork, Interior - Excellent Condition, Tyre condition Excellent, 12 Month warranty available - JBR/Aldermore/Black Horse Partner. Major credit/debit cards accepted.",
    specifications: [
      "Cherry Tree Exterior Paint",
      "Cavallino Stitched On Headrest",
      "Alarm Upgrade Volumetric & Tilt Sensors",
      "Dark Anodised Brake Calipers",
      "Black Textured Tailpipe Finisher",
      "Sports Seat - Isofix",
      "15 Spoke Satin Black Dt Bronze Tinted Wheels",
      "Q By Aston Martin",
      "Black Damson Leather Interior",
      "Cream Truffle Stitching",
      "Graduated Z Quilt Stitching",
      "Obsidian Black Carpet Colour",
      "Black Side Window Finisher",
      "Full Length Herringbone",
      "2 + 2 Seating Arrangement",
    ],
  },
  {
    id: 61080,
    name: "Lamborghini Aventador SV LP750-4",
    mileage: 1496,
    year: 2016,
    price: 359900,
    image: "https://gvelondon.com/wp-content/uploads/2022/11/9-15.jpg",
    overview:
      "This Lamborghini Aventador LP 750-4 SV (Short for Superveloce) has striking looks, a scintillating engine and impressive grip. It is one of the fastest, most agile and attractive cars from the Italian manufacturer. The Aventador SV is exclusive, pushes limits with usable downforce, has delicate steering, huge grip and balance giving it epic performance. This Aventador LP 750-4 SV Roadster includes optional extras such as a Transparent Engine Bonnet, Dianthus Forged 20'/21' High Gloss Black Alloys, Sensonum Premium Sound System and Branding Package With Alcantara. The paint this Aventador SV is finished in is an exquisite Blue Caelum, with matching callipers and interior stitching. Under the bonnet is a whopping 6.5 litre V12 followed by a freer-following exhaust producing 740bhp. This engine is capable of achieving crazy speeds of 218mph, 0-60 time of astonishingly only 2.7 Seconds. The power is transmitted through all four wheels and a seven-speed gearbox, meaning it can conjure tracition even through wet roads. Amazingly, it also has a carbon chassis, making a 50kg weight reduction and more aero making the car full of feel. Walk around video available upon request. Nationwide delivery available. All vehicles undergo a full visual and mechanical health check by GVE Servicing and preparation by GVE detailing. Get in touch with any customisation or servicing needs. Please call to confirm specifications as variations can occur. Excellent bodywork, Interior - Excellent Condition, Tyre condition Excellent, 12 Month warranty available - JBR/Aldermore/Black Horse Partner. Major credit/debit cards accepted.",
    specifications: [
      "Blue Caelum - Main Paint",
      "Fixed Rear Intake In Visible Carbon Fibre",
      "Transparent Engine Bonnet",
      "X-Frame & T-Engine Cover In Carbon Fibre",
      "Dianthus Forged 20'/21' High Gloss Black With Central Locking",
      "Big SV Logo",
      "Rear View Camera",
      "Electric And Heated Comfort Seats With Carbon Details",
      "Sensonum Premium Sound System",
      "LIS With Navigation System And DAB Radio",
      "Footplate In Carbon Fibre",
      "Multifunctional Steering Wheel In Alcantara With Smooth Leather Inserts",
      "Branding Package With Alcantara",
    ],
  },
  {
    id: 19230,
    name: "Mclaren 675LT Spider",
    mileage: 487,
    year: 2016,
    price: 274900,
    image: "https://gvelondon.com/wp-content/uploads/2022/07/9-36.jpg",
    overview:
      "This McLaren 675LT Spider, finished in Napier Green, has been fitted with 10 Spoke Ultra Light Weight Silver Wheels and Napier Green brake calipers as well as ceramic brakes, a sports exhaust and soft close doors. The car has a huge carbon fibre specification including the front bumper and end plate, side skirts and intakes, rear diffuser and door mirrors. The Carbon Black alcantara and leather interior has been finished with Napier Green contrast stitching and includes racing seats, a Meridian Surround Sound System, an ashtray, branded floor mats, McLaren Track Telemetry (including an App and Cameras) and the Stealth pack. The interior also has carbon fibre upgrades including the centre console, steering wheel, paddle shifters and door inserts. DAB radio, electric windows, a satellite navigation system and a touch screen monitor have also been included. The 3.8L Turbo-Charged V8 Engine produces 666 bhp and has a top speed of 203 mph, reaching 0-62mph in 2.9 seconds. Walk around video available upon request. Nationwide delivery available. All vehicles undergo a full visual and mechanical health check by GVE Servicing and preparation by GVE detailing. Get in touch with any customisation or servicing needs. Please call to confirm specifications as variations can occur. Excellent bodywork, Interior - Excellent Condition, Tyre condition Excellent, 12 Month warranty available - JBR/Aldermore/Black Horse Partner. Major credit/debit cards accepted.",
    specifications: [
      "McLaren Track Telemetry - App and Cameras",
      "Carbon Fibre Exterior Upgrade Pack",
      "Stealth Pack",
      "Stealth Badge Set",
      "Extended Carbon Fibre Interior Upgrade",
      "Branded Floor Mat Set",
      "Ashtray",
      "Carbon Black Alcantara and Leather Interior",
      "Meridian Surround Sound System",
      "Racing Seats",
      "Extended Steering Wheel Panels",
      "Napier Green Contrast Stitching",
      "Carbon Fibre Door Inserts",
      "Parking Sensors and Rear View Camera",
      "Napier Green Exterior Paint",
      "Napier Green Brake Calipers",
      "Carbon Fibre Door Mirrors",
      "Sports Exhaust",
      "Carbon Fibre Front Bumper End Plate",
      "Carbon Fibre Front Splitter",
      "Carbon Fibre Rear Bumper",
      "Carbon Fibre Side Intake",
      "Carbon Fibre Side Skirt",
      "Carbon Fibre Diffuser",
    ],
  },
  {
    id: 19230,
    name: "Mclaren 675LT Spider",
    mileage: 487,
    year: 2016,
    price: 274900,
    image: "https://gvelondon.com/wp-content/uploads/2022/07/9-36.jpg",
    overview:
      "This McLaren 675LT Spider, finished in Napier Green, has been fitted with 10 Spoke Ultra Light Weight Silver Wheels and Napier Green brake calipers as well as ceramic brakes, a sports exhaust and soft close doors. The car has a huge carbon fibre specification including the front bumper and end plate, side skirts and intakes, rear diffuser and door mirrors. The Carbon Black alcantara and leather interior has been finished with Napier Green contrast stitching and includes racing seats, a Meridian Surround Sound System, an ashtray, branded floor mats, McLaren Track Telemetry (including an App and Cameras) and the Stealth pack. The interior also has carbon fibre upgrades including the centre console, steering wheel, paddle shifters and door inserts. DAB radio, electric windows, a satellite navigation system and a touch screen monitor have also been included. The 3.8L Turbo-Charged V8 Engine produces 666 bhp and has a top speed of 203 mph, reaching 0-62mph in 2.9 seconds. Walk around video available upon request. Nationwide delivery available. All vehicles undergo a full visual and mechanical health check by GVE Servicing and preparation by GVE detailing. Get in touch with any customisation or servicing needs. Please call to confirm specifications as variations can occur. Excellent bodywork, Interior - Excellent Condition, Tyre condition Excellent, 12 Month warranty available - JBR/Aldermore/Black Horse Partner. Major credit/debit cards accepted.",
    specifications: [
      "McLaren Track Telemetry - App and Cameras",
      "Carbon Fibre Exterior Upgrade Pack",
      "Stealth Pack",
      "Stealth Badge Set",
      "Extended Carbon Fibre Interior Upgrade",
      "Branded Floor Mat Set",
      "Ashtray",
      "Carbon Black Alcantara and Leather Interior",
      "Meridian Surround Sound System",
      "Racing Seats",
      "Extended Steering Wheel Panels",
      "Napier Green Contrast Stitching",
      "Carbon Fibre Door Inserts",
      "Parking Sensors and Rear View Camera",
      "Napier Green Exterior Paint",
      "Napier Green Brake Calipers",
      "Carbon Fibre Door Mirrors",
      "Sports Exhaust",
      "Carbon Fibre Front Bumper End Plate",
      "Carbon Fibre Front Splitter",
      "Carbon Fibre Rear Bumper",
      "Carbon Fibre Side Intake",
      "Carbon Fibre Side Skirt",
      "Carbon Fibre Diffuser",
    ],
  },
];

module.exports = cars;
